name: Sync Rules
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

# 核心：强制开启写入权限，防止 128 错误
permissions:
  contents: write

jobs:
  merge_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Merge
        run: |
          curl -sL "hhttps://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China.list" > temp.txt
          #curl -sL "https://githubusercontent.com" >> temp.txt
          grep -E '^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-KEYWORD)' temp.txt | sed 's/,DIRECT//g' | sort -u > cn_merged.txt

      - name: Push to Repository
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add cn_merged.txt
          # 这里防止没有变化时报错
          git commit -m "Update: $(date)" || exit 0
          # 明确指定推送分支为 main
          git push origin main
